- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true

  - name: print user o/p
    ansible.builtin.debug:
      msg: "user info: {{user}}"

  - name: create user
    ansible.builtin.command: useradd expense
  when: user.rc != 0