- name: create ec2 and r53
  hosts: local
  connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    subnet_id: "subnet-0cfffd2292d4c9e00"
    sg_id: "sg-07d8fb22810134e87"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      region: "us-east-1"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group:  "{{ sg_id }}"
      image_id:  "{{ ami_id}}"
    loop:  "{{ instances }}"
    register: ec2_instances
