- name: prompt from user
  hosts: web
  become: yes
  vars_prompt:
  - name: course
    prompt: enter course name
    private: false
  - name: duration
    prompt: enter duration
    private: false
  tasks:
  - name: debug from user
    ansible.builtin.debug:
      msg: "the course name is {{course}} and duration is {{duration}}"
