- name: prompt from user
  hosts: web
  become: yes
  vars:
    course: "devops"
    duration: "120 days"
  tasks:
  - name: debug from user
    ansible.builtin.debug:
      msg: "the course name is {{course}} and duration is {{duration}}"
  - name: debug from user task vars
    vars:
      course: "AWS"
    ansible.builtin.debug:
      msg: "the course name is {{course}} and duration is {{duration}}"